services:
  backend:
    build: ./server
    container_name: mern-backend
    network_mode: host
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: mern-frontend
    ports:
      - "3000:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend